server:
  port: ${APPLICATION_PORT:8082}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:54326/postgres?currentSchema=market_service_schema}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml

feign:
  client:
    config:
      auth-service:
        url: ${AUTH_SERVICE_URL:http://localhost:8081}
      delivery-service:
        url: ${DELIVERY_SERVICE_URL:http://localhost:8083}

kafka:
  consumer:
    delivery-status-event:
      topic: ${DELIVERY_STATUS_EVENT_TOPIC:delivery-status-event-local}
      consumer-group-id: ${DELIVERY_STATUS_EVENT_CONSUMER_GROUP:market-service-delivery-status-event-group-local}
      cluster:
        bootstrap-servers: ${DELIVERY_STATUS_EVENT_BOOTSTRAP_SERVERS:localhost:9092}

logging:
  level:
    com.bmo.common.market_service: ${APPLICATION_DEBUG_LEVEL:DEBUG}