server:
  port: ${SERVICE_PORT:8082}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:54326/postgres?currentSchema=market_service_schema}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml

feign:
  client:
    config:
      auth-service:
        url: http://localhost:8081

jwt:
  valid-duration: PT24H
  secret: secret